use OnRets 
insert into Area values(1,'华北','北京','北京','朝阳区')
insert into Area values(1,'华北','北京','北京','海淀区')
insert into Area values(1,'华北','河北省','石家庄','新华区')
insert into Area values(1,'东北','辽宁','沈阳市','和平区')
insert into Area values(1,'东北','黑龙江省','哈尔滨市','南岗区')
insert into Area values(1,'华中','河南省','信阳市','固始县')
insert into Area values(1,'华中','湖南省','长沙市','芙蓉区')
insert into Area values(1,'华南','广东省','广州市','白云区')
insert into Area values(1,'华南','广西','南宁市','青秀区')
insert into Area values(1,'华东','浙江省','杭州市','西湖区')
insert into Area values(1,'华东','江苏省','南京市','栖霞区')
insert into Area values(1,'西南','四川省','成都市','武侯区')
insert into Area values(1,'西南','云南省','昆明市','五华区区')
insert into Area values(1,'西北','甘肃省','兰州市','城关区')
insert into Area values(1,'西北','陕西省','西安市','雁塔区')